### ISSUE TITLE
cargo 1.78.0 fails to compile the rust code due to "{{" in the template Cargo.toml

### ISSUE THREAD

**Issue by gravityismagnetism** [ThorstenHans/spin-htmx#1]
kirk@Kirk-AI:~/src/wasm$ git clone --depth 1 https://github.com/ThorstenHans/spin-htmx.git
Cloning into 'spin-htmx'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 21 (delta 1), reused 17 (delta 0), pack-reused 0
Receiving objects: 100% (21/21), 44.67 KiB | 1.59 MiB/s, done.
Resolving deltas: 100% (1/1), done.
kirk@Kirk-AI:~/src/wasm$ ls 
helloworld  shopping-list  spin-htmx
kirk@Kirk-AI:~/src/wasm$ cd spin-htmx
kirk@Kirk-AI:~/src/wasm/spin-htmx$ ls
api  app  migration.sql  README.md  spin.toml
kirk@Kirk-AI:~/src/wasm/spin-htmx$ spin build
Building component api with `cargo build --target wasm32-wasi --release`
Working directory: "./api"
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../../.cargo/git/checkouts/spin-91500438ac5656d2/1d72f1c/templates/http-rust/content/Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../../.cargo/git/checkouts/spin-91500438ac5656d2/1d72f1c/templates/redis-rust/content/Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |

kirk@Kirk-AI:~/src/wasm/spin-htmx$ cargo -V
cargo 1.78.0 (54d8815d0 2024-03-26)

**Comment by gravityismagnetism** [comment]
The example still functions, so it must not be a fatal compile error.

**Comment by ThorstenHans** [comment]
Thanks for flagging this @gravityismagnetism I've updated the sample to the latest `spin-sdk` and fixed the issue
